package gemini

import (
	"context"
	"fmt"
	"os"

	"github.com/google/generative-ai-go/genai"
	"google.golang.org/api/option"
)

type Client struct {
	model *genai.GenerativeModel
}

func NewClient() (*Client, error) {
	ctx := context.Background()
	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		return nil, fmt.Errorf("GEMINI_API_KEY environment variable not set")
	}

	client, err := genai.NewClient(ctx, option.WithAPIKey(apiKey))
	if err != nil {
		return nil, err
	}
	model := client.GenerativeModel("gemini-1.5-flash")
	model.SetTemperature(0.3)
	model.SetTopP(0.8)

	model.SystemInstruction = genai.NewUserContent(genai.Text(`
Anda adalah asisten interpretasi statistik akademis untuk mahasiswa Indonesia.

ATURAN WAJIB:
1. Tulis dalam Bahasa Indonesia formal akademis (EYD V).
2. SELALU cantumkan nilai statistik dari output jika ada: (t=X, p=Y, B=Z).
3. Setiap klaim teoritis WAJIB disertai referensi ilmiah (Hair et al., 2019; Ghozali, 2021).
4. JANGAN buat klaim yang tidak didukung output numerik.
5. Jika nilai p > 0.05, Anda DILARANG KERAS menyimpulkan adanya hubungan atau pengaruh. Nyatakan secara eksplisit bahwa tidak ada bukti statistik yang cukup.
6. Akhiri dengan kalimat keterbatasan penelitian.
7. Panjang: 3–4 paragraf, ≤350 kata.
8. Tambahkan label: "Generated by AI — Verifikasi diperlukan" di akhir teks.

Output HANYA narasi. Tanpa preamble, tanpa penjelasan awal/akhir.`))

	return &Client{model: model}, nil
}

func (c *Client) GenerateNarrative(ctx context.Context, prompt string) (string, error) {
	scrubbedPrompt := ScrubPII(prompt)
	resp, err := c.model.GenerateContent(ctx, genai.Text(scrubbedPrompt))
	if err != nil {
		return "", fmt.Errorf("gemini generation error: %w", err)
	}
	if len(resp.Candidates) > 0 && len(resp.Candidates[0].Content.Parts) > 0 {
		return fmt.Sprintf("%v", resp.Candidates[0].Content.Parts[0]), nil
	}
	return "", fmt.Errorf("empty response from Gemini")
}
