package gemini

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"google.golang.org/genai"
)

type Client struct {
	client    *genai.Client
	modelName string
}

type NarrativeOutput struct {
	StatusIntegritas   string `json:"status_integritas"`
	ParagrafPembuka    string `json:"paragraf_pembuka"`
	AnalisisStatistik  string `json:"analisis_statistik"`
	KesimpulanAkademis string `json:"kesimpulan_akademis"`
}

func NewClient() (*Client, error) {
	ctx := context.Background()
	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		return nil, fmt.Errorf("GEMINI_API_KEY environment variable not set")
	}

	client, err := genai.NewClient(ctx, &genai.ClientConfig{
		APIKey: apiKey,
	})
	if err != nil {
		return nil, err
	}

	return &Client{
		client:    client,
		modelName: "gemini-1.5-flash",
	}, nil
}

func (c *Client) getSystemInstruction() *genai.Content {
	return &genai.Content{
		Parts: []*genai.Part{
			{
				Text: `Anda adalah asisten interpretasi statistik akademis untuk mahasiswa Indonesia.

ATURAN WAJIB:
1. Tulis dalam Bahasa Indonesia formal akademis (EYD V).
2. SELALU cantumkan nilai statistik dari output jika ada: (t=X, p=Y, B=Z).
3. Setiap klaim teoritis WAJIB disertai referensi ilmiah (Hair et al., 2019; Ghozali, 2021).
4. JANGAN buat klaim yang tidak didukung output numerik.
5. Jika nilai p > 0.05, Anda DILARANG KERAS menyimpulkan adanya hubungan atau pengaruh. Nyatakan secara eksplisit bahwa tidak ada bukti statistik yang cukup.
6. Akhiri dengan kalimat keterbatasan penelitian.
7. Panjang: 3–4 paragraf, ≤350 kata.
8. Tambahkan label: "Generated by AI — Verifikasi diperlukan" di akhir teks.

Output HANYA narasi. Tanpa preamble, tanpa penjelasan awal/akhir.`,
			},
		},
	}
}

func (c *Client) GenerateNarrative(ctx context.Context, prompt string) (string, error) {
	scrubbedPrompt := ScrubPII(prompt)
	resp, err := c.client.Models.GenerateContent(
		ctx,
		c.modelName,
		genai.Text(scrubbedPrompt),
		&genai.GenerateContentConfig{
			SystemInstruction: c.getSystemInstruction(),
			Temperature:       genai.Ptr(float32(0.3)),
			TopP:              genai.Ptr(float32(0.8)),
			Tools: []*genai.Tool{
				{
					GoogleSearch: &genai.GoogleSearch{},
				},
			},
		},
	)
	if err != nil {
		return "", fmt.Errorf("gemini generation error: %w", err)
	}
	if len(resp.Candidates) > 0 && len(resp.Candidates[0].Content.Parts) > 0 {
		return resp.Candidates[0].Content.Parts[0].Text, nil
	}
	return "", fmt.Errorf("empty response from Gemini")
}

func (c *Client) GenerateStructuredNarrative(ctx context.Context, prompt string) (NarrativeOutput, error) {
	scrubbedPrompt := ScrubPII(prompt)
	resp, err := c.client.Models.GenerateContent(
		ctx,
		c.modelName,
		genai.Text(scrubbedPrompt),
		&genai.GenerateContentConfig{
			SystemInstruction: c.getSystemInstruction(),
			Temperature:       genai.Ptr(float32(0.3)),
			TopP:              genai.Ptr(float32(0.8)),
			ResponseMIMEType:  "application/json",
			ResponseSchema: &genai.Schema{
				Type: genai.TypeObject,
				Properties: map[string]*genai.Schema{
					"status_integritas":   {Type: genai.TypeString},
					"paragraf_pembuka":    {Type: genai.TypeString},
					"analisis_statistik":  {Type: genai.TypeString},
					"kesimpulan_akademis": {Type: genai.TypeString},
				},
				Required: []string{"status_integritas", "paragraf_pembuka", "analisis_statistik", "kesimpulan_akademis"},
			},
			Tools: []*genai.Tool{
				{
					GoogleSearch: &genai.GoogleSearch{},
				},
			},
		},
	)
	if err != nil {
		return NarrativeOutput{}, fmt.Errorf("gemini structured generation error: %w", err)
	}

	if len(resp.Candidates) == 0 || len(resp.Candidates[0].Content.Parts) == 0 {
		return NarrativeOutput{}, fmt.Errorf("empty response from Gemini")
	}

	rawText := resp.Candidates[0].Content.Parts[0].Text
	var output NarrativeOutput
	if err := json.Unmarshal([]byte(rawText), &output); err != nil {
		return NarrativeOutput{}, fmt.Errorf("failed to unmarshal structured narrative: %w, raw response: %s", err, rawText)
	}

	return output, nil
}
